// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDVdfZaPsL7mvvdRffHXGx_HxwzB2RREhE',
    appId: '1:335240935782:web:223e22c4c82e738e7e70a7',
    messagingSenderId: '335240935782',
    projectId: 'flutter-coding-bd7a7',
    authDomain: 'flutter-coding-bd7a7.firebaseapp.com',
    storageBucket: 'flutter-coding-bd7a7.firebasestorage.app',
    measurementId: 'G-1YW27LZZBG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCCzFsZvUiH8p1DE57cRNzXAwFXv3WMAy0',
    appId: '1:335240935782:android:a8034271887f27897e70a7',
    messagingSenderId: '335240935782',
    projectId: 'flutter-coding-bd7a7',
    storageBucket: 'flutter-coding-bd7a7.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCeZ_QwROe3rgCU_r7zLCEFW2JV9S7naE0',
    appId: '1:335240935782:ios:76bf58768c7b4bb37e70a7',
    messagingSenderId: '335240935782',
    projectId: 'flutter-coding-bd7a7',
    storageBucket: 'flutter-coding-bd7a7.firebasestorage.app',
    iosBundleId: 'com.example.flutterCoding',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCeZ_QwROe3rgCU_r7zLCEFW2JV9S7naE0',
    appId: '1:335240935782:ios:76bf58768c7b4bb37e70a7',
    messagingSenderId: '335240935782',
    projectId: 'flutter-coding-bd7a7',
    storageBucket: 'flutter-coding-bd7a7.firebasestorage.app',
    iosBundleId: 'com.example.flutterCoding',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDVdfZaPsL7mvvdRffHXGx_HxwzB2RREhE',
    appId: '1:335240935782:web:d29fb76320f123f97e70a7',
    messagingSenderId: '335240935782',
    projectId: 'flutter-coding-bd7a7',
    authDomain: 'flutter-coding-bd7a7.firebaseapp.com',
    storageBucket: 'flutter-coding-bd7a7.firebasestorage.app',
    measurementId: 'G-Q1NL5B59S8',
  );
}
